version: 2
updates:

  # Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Project
  - package-ecosystem: npm
    directory: /Server
    schedule:
      interval: monthly
