version: 2
updates:

  # Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Project
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly

  # Client
  - package-ecosystem: npm
    directory: /client/
    schedule:
      interval: monthly

  # Server
  - package-ecosystem: npm
    directory: /server/
    schedule:
      interval: monthly
