# This workflow builds, tests & deploys the project.

name: Automate

on:
  push:
    paths:
      - 'Server/**'
      - 'Client/**'
      - 'Dockerfile'
      - '.github/workflows/automate.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  ARTIFACT_SERVER_NAME: LiveChat-Server
  ARTIFACT_CLIENT_NAME: LiveChat-Client
  DOCKER_REGISTRY_DOMAIN: ghcr.io
  DOCKER_IMAGE_NAME: livechat

jobs:
  client:
    name: Client
    runs-on: ubuntu-22.04
    env:
      DIRECTORY_CLIENT: ./Client/
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ${{ env.DIRECTORY_CLIENT }}
          css: true

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_CLIENT_NAME }}
          path: ${{ env.DIRECTORY_CLIENT }}

  server:
    name: Server
    runs-on: ubuntu-22.04
    env:
      DIRECTORY_SERVER: ./Server/
    defaults:
      run:
        working-directory: ./Server/
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx eslint ./source/

      - name: Compile TypeScript
        run: npx tsc

      - name: Generate Express session secret
        id: express
        run: |
          EXPRESS_SESSION_SECRET=$(openssl rand -hex 16)
          echo "EXPRESS_SESSION_SECRET=${EXPRESS_SESSION_SECRET}" >> $GITHUB_OUTPUT

      - name: Create environment variables file
        run: cp --verbose --archive ./production.env ./test.env

      - name: Run unit & integration tests
        env:
          HTTP_SERVER_ADDRESS: 127.0.0.1
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_DATABASE: LiveChat-Test
          MONGO_USER_NAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_USER_PASS: ${{ secrets.MONGO_PASSWORD }}
          EXPRESS_SESSION_SECRET: ${{ steps.express.outputs.EXPRESS_SESSION_SECRET }}
          EXPRESS_CLIENT_DIRECTORY: ../Client
          EXPRESS_COOKIE_DOMAIN: 127.0.0.1
        run: npm test

      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: Server-Log
          path: ${{ env.DIRECTORY_SERVER }}/logs/server.log

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_SERVER_NAME }}
          path: |
            ${{ env.DIRECTORY_SERVER }}/dist/
            ${{ env.DIRECTORY_SERVER }}/package.json
            ${{ env.DIRECTORY_SERVER }}/package-lock.json
            ${{ env.DIRECTORY_SERVER }}/production.env

  docker:
    name: Docker
    runs-on: ubuntu-22.04
    needs:
      - client
      - server
    concurrency:
      group: docker
      cancel-in-progress: true
    env:
      DIRECTORY_BUILDS: ./builds/
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY_DOMAIN }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download server build
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_SERVER_NAME }}
          path: ${{ env.DIRECTORY_BUILDS }}/server/

      - name: Download client build
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_CLIENT_NAME }}
          path: ${{ env.DIRECTORY_BUILDS }}/client/

      - name: Remove server unit & integration tests
        run: rm --verbose --recursive ${{ env.DIRECTORY_BUILDS }}/server/dist/tests/

      - name: Create metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY_DOMAIN }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
          labels: |
            org.opencontainers.image.title=Live Chat
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            com.docker.extension.publisher-url=https://viral32111.com

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Dockerfile
          context: ${{ env.DIRECTORY_BUILDS }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          pull: true

      - name: Delete untagged Docker images
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ env.DOCKER_IMAGE_NAME }}
          cut-off: 0 seconds ago UTC
          keep-at-least: 1
          untagged-only: true
          account-type: personal
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_PACKAGES }}

  deploy-google:
    name: Deploy to Google Cloud
    runs-on: ubuntu-22.04
    needs: docker
    concurrency:
      group: deploy-google
      cancel-in-progress: true
    env:
      GOOGLE_CLOUD_INSTANCE: livechat-server
      GOOGLE_CLOUD_INSTANCE_ZONE: europe-west2-c
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate using JSON service account key
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Compute Engine
        run: gcloud compute instances update-container ${{ env.GOOGLE_CLOUD_INSTANCE }} --zone ${{ env.GOOGLE_CLOUD_INSTANCE_ZONE }} --container-image ${{ env.DOCKER_REGISTRY_DOMAIN }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest

  deploy-github:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    needs: client
    concurrency:
      group: deploy-github
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      DIRECTORY_BUILD: ./build/
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download client build
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_CLIENT_NAME }}
          path: ${{ env.DIRECTORY_BUILD }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.DIRECTORY_BUILD }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Run Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        with:
          url: ${{ steps.deployment.outputs.page_url }}
          threshold: 70
          strategy: desktop
          key: ${{ secrets.GOOGLE_PAGE_SPEED_INSIGHTS_API_KEY }}
