name: CI

on:
  push:
    paths:
      - '**'
    branches:
      - '**'
    tags:
      - '*.*.*'
  workflow_dispatch:

env:
  ARTIFACT_NAME: live-chat
  DOCKER_IMAGE_NAME: live-chat
  DOCKER_REGISTRY_DOMAIN: ghcr.io

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    services:
      mongodb:
        image: mongo:6-jammy
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ github.sha }}-user
          MONGO_INITDB_ROOT_PASSWORD: ${{ github.sha }}-password
          MONGO_INITDB_DATABASE: ${{ github.sha }}-database
        ports:
          - 27017:27017
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: client/dist
          css: true

      - name: Generate secrets
        id: generate
        run: |
          echo "EXPRESS_SESSION_SECRET=$(openssl rand -hex 16)" >> $GITHUB_OUTPUT
          echo "MONGODB_SECRET=$(openssl rand -hex 16)" >> $GITHUB_OUTPUT

      - name: Run tests
        env:
          NODE_ENV: test
          EXPRESS_LISTEN_ADDRESS: 127.0.0.1 # Shouldn't be needed, as this is the default
          EXPRESS_CLIENT_DIRECTORY: client/dist
          MONGODB_SCHEME: mongodb # Shouldn't be needed, as this is the default
          MONGODB_SERVER_ADDRESS: 127.0.0.1 # Shouldn't be needed, as this is the default
          MONGODB_USER_NAME: ${{ github.sha }}-user
          MONGODB_USER_PASSWORD: ${{ github.sha }}-password
          MONGODB_DATABASE: ${{ github.sha }}-database
          MONGODB_SECRET: ${{ steps.generate.outputs.MONGODB_SECRET }}
          EXPRESS_SESSION_COOKIE_DOMAIN: 127.0.0.1 # Shouldn't be needed, as this is the default
          EXPRESS_SESSION_SECRET: ${{ steps.generate.outputs.EXPRESS_SESSION_SECRET }}
        run: yarn test

      - name: Remove server tests
        working-directory: server
        run: rm --verbose --recursive dist/tests

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            client/dist
            client/package.json
            server/dist
            server/package.json
            .env.example
            package.json
            LICENSE.txt

  docker:
    name: Docker
    runs-on: ubuntu-22.04
    needs: build-test
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' && !startsWith( github.ref_name, 'dependabot/' ) }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY_DOMAIN }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact

      - name: Create metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY_DOMAIN }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
          labels: |
            org.opencontainers.image.title=Live Chat
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            com.docker.extension.publisher-url=https://viral32111.com

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' && !startsWith( github.ref_name, 'dependabot/' ) }}
          file: Dockerfile
          context: artifacts
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          no-cache: true
          pull: true

      - name: Delete untagged Docker images
        if: ${{ github.event_name != 'pull_request' && !startsWith( github.ref_name, 'dependabot/' ) }}
        uses: snok/container-retention-policy@v2
        with:
          image-names: ${{ env.DOCKER_IMAGE_NAME }}
          cut-off: 24 hours ago UTC
          keep-at-least: 1
          untagged-only: true
          skip-tags: latest
          account-type: personal
          token: ${{ secrets.PACKAGES_PERSONAL_ACCESS_TOKEN }}

  deploy-github:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: build-test
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: github-pages
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: artifact/client/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Run Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        with:
          url: ${{ steps.deployment.outputs.page_url }}
          threshold: 70
          strategy: desktop
          key: ${{ secrets.GOOGLE_PAGE_SPEED_INSIGHTS_API_KEY }}
