# This action validates and error-checks HTML pages using the W3C validator.

name: Client

on:
  push:
    paths:
      - 'Client/**'
      - '.github/workflows/client.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  validate-html:
    name: Validate HTML
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./Client/
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./Client
          css: true

      - name: Upload validation log
        uses: actions/upload-artifact@v3
        with:
          name: Log
          path: ./log.log

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-22.04
    needs: validate-html
    concurrency:
      group: deploy-to-pages
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: ./Client/
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload website
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./Client/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Run Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        with:
          url: ${{ steps.deployment.outputs.page_url }}
          threshold: 70
          strategy: desktop
          key: ${{ secrets.GOOGLE_PAGE_SPEED_INSIGHTS_API_KEY }}
