# This action builds the server-side code.

name: Server

on:
  push:
    paths:
      - 'Server/**'
      - '.github/workflows/server.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  ARTIFACT_NAME: LiveChat-Server
  PUBLISHER_WEBSITE: https://viral32111.com

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./Server/
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx eslint ./source/

      - name: Compile TypeScript
        run: npx tsc

      - name: Generate Express session secret
        id: express
        run: |
          openssl version
          openssl help
          openssl help rand

          EXPRESS_SESSION_SECRET=$(openssl rand -hex 16)
          echo "EXPRESS_SESSION_SECRET=${EXPRESS_SESSION_SECRET}" >> $GITHUB_OUTPUT

          openssl rand -hex 16
          echo "The secret is '${EXPRESS_SESSION_SECRET}'"

      - name: Create environment variables file
        run: cp --verbose --archive ./production.env ./test.env

      - name: Run Unit Tests
        env:
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_DATABASE: LiveChat-Test
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          EXPRESS_SESSION_SECRET: ${{ steps.express.outputs.EXPRESS_SESSION_SECRET }}
        run: npm test

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ./Server/dist/
            ./Server/package.json
            ./Server/package-lock.json
            ./Server/production.env

  docker:
    name: Docker Image
    runs-on: ubuntu-22.04
    needs: build
    env:
      REGISTRY_NAME: ghcr.io
      IMAGE_NAME: livechat
    defaults:
      run:
        working-directory: ./Server/
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./Build/

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create metadata for Docker image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_NAME }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
          labels: |
            org.opencontainers.image.title=Live Chat
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            com.docker.extension.publisher-url=${{ env.PUBLISHER_WEBSITE }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Server/Dockerfile
          context: ./Build/
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          no-cache: true
          pull: true

      - name: Delete untagged Docker images
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ env.IMAGE_NAME }}
          cut-off: 0 seconds ago UTC
          keep-at-least: 1
          untagged-only: true
          account-type: personal
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_PACKAGES }}
